services:

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - PORT=8080

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - PORT=3000

  database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=momentum
