services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=80

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PORT=80

  database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=momentum
