spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  application:
    name: momentum


  liquibase:
    change-log: classpath:db/changelog/master_changelog.yml
    drop-first: true #Toggle on if you want to rebuild the database.


